# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: package with pyinstaller
      run: |
        nuitka --standalone --disable-console --enable-plugin=tk-inter --include-data-dir=./icons/=./icons/ --remove-output  gui.py
    - name: zip binary
      run: Compress-Archive -Path dist/excel-duplicate-marker -Destination excel-duplicate-marker.zip
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: excel-duplicate-marker.zip
        asset_name: excel-duplicate-marker.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: ""
