# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: "3.11.0"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Chocolatey Action
      uses: crazy-max/ghaction-chocolatey@v3.0.0
      with:
        args: install -y python3 visualstudio2019-workload-vctools
    - name: download pytinstaller source code
      working-directory: ${{github.workspace}}
      run: Invoke-WebRequest -Uri "https://github.com/pyinstaller/pyinstaller/archive/refs/tags/v6.3.0.zip" -OutFile output.zip
    - name: unzip pytinstaller source code
      working-directory: ${{github.workspace}}
      run: |
        Expand-Archive -Path output.zip -DestinationPath pyinstaller
        ls .
